### ISSUE TITLE
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classic

### ISSUE THREAD

**Issue by aroltsch** [aroltsch/checkers#13]
## NSD Contact Information
**NSD Ticket #:**

**NSD Contact Name:**

**NSD Email:**

## Reporter Information
**User Name:** CSFLOW8 (283)

**Department:**

**Office Location:**

**Contact Number:**

**Email Address:** anya@example.com

## Issue Description
**Type of Bug:**
- [ ] Performance
- [ ] Security
- [ ] Functional

**Severity Level:**
- [ ]    5 - Data loss, data corruption or system unavailable
- [ ]    4 - Important functionality is unavailable with no workaround
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround

**Details:**
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

## Sub-Tasks
- [ ] Send Reporter Acknowledgement
- [ ] Assess Issue
- [ ] Assign to Team
- [ ] Received Team Acknowledgement
- [ ] Update Reporter
- [ ] Resolve Issue
- [ ] Received Completion Notice
- [ ] Update Reporter - Issue Complete
- [ ] Close NSD ticket, if applicable
- [ ] Confirm/Update Knowledge Base

# Related Issues
