### ISSUE TITLE
It is a long established fact that a reader will be distracted by the readable content of a page when

### ISSUE THREAD

**Issue by aroltsch** [aroltsch/checkers#8]
## NSD Contact Information
**NSD Ticket #:**

**NSD Contact Name:**

**NSD Email:**

## Reporter Information
**User Name:**

**Department:**

**Office Location:**

**Contact Number:**

**Email Address:** anya@example.com

## Issue Description
**Type of Bug:**
- [ ] Performance
- [ ] Security
- [ ] Functional

**Severity Level:**
- [ ]    5 - Data loss, data corruption or system unavailable
- [ ]    4 - Important functionality is unavailable with no workaround
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround

**Details:**
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

## Sub-Tasks
- [ ] Send Reporter Acknowledgement
- [ ] Assess Issue
- [ ] Assign to Team
- [ ] Received Team Acknowledgement
- [ ] Update Reporter
- [ ] Resolve Issue
- [ ] Received Completion Notice
- [ ] Update Reporter - Issue Complete
- [ ] Close NSD ticket, if applicable
- [ ] Confirm/Update Knowledge Base

# Related Issues
